version: '3.8'

services:
  flood-prediction:
    build: .
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=production
      - OPENWEATHER_API_KEY=your_api_key_here
      - TELEGRAM_BOT_TOKEN=your_bot_token_here
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./models:/app/models
      - ./alerts:/app/alerts
    restart: unless-stopped

  # Optional: Add nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flood-prediction
    restart: unless-stopped
