services:
  - type: web
    name: ai-flood-prediction-system
    env: python
    runtime: python-3.11.9
    buildCommand: pip install -r requirements-production.txt
    startCommand: python app.py
    healthCheckPath: /api/status
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
      - key: OPENWEATHER_API_KEY
        value: 4d6eb4cfda31ca9dd9e06e83566e0e7a
    scaling:
      minInstances: 1
      maxInstances: 3
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
